
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 19 2025 01:53:04

// Verification Directory fv/synth_wrapper 

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_119), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (n_118), .Q (carry));
  sky130_fd_sc_hd__nand4_2 g5542(.A (n_117), .B (n_107), .C (n_102), .D
       (n_110), .Y (n_119));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_115), .Q (result[2]));
  sky130_fd_sc_hd__nand3_1 g5544(.A (n_109), .B (n_114), .C (n_84), .Y
       (n_118));
  sky130_fd_sc_hd__clkinv_1 g5545(.A (n_116), .Y (n_117));
  sky130_fd_sc_hd__o21ai_2 g5546(.A1 (n_79), .A2 (n_112), .B1 (n_113),
       .Y (n_116));
  sky130_fd_sc_hd__nand4_1 g5547(.A (n_97), .B (n_106), .C (n_90), .D
       (n_111), .Y (n_115));
  sky130_fd_sc_hd__nand2b_1 g5548(.A_N (n_79), .B (n_112), .Y (n_114));
  sky130_fd_sc_hd__nand2_1 g5549(.A (n_112), .B (n_75), .Y (n_113));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_108), .Q (result[1]));
  sky130_fd_sc_hd__nand2_1 g5551(.A (n_101), .B (n_44), .Y (n_111));
  sky130_fd_sc_hd__nand2_2 g5552(.A (n_98), .B (n_0), .Y (n_112));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_105), .Q (result[0]));
  sky130_fd_sc_hd__nand3_1 g5554(.A (n_80), .B (n_78), .C (n_19), .Y
       (n_110));
  sky130_fd_sc_hd__nand2_1 g5555(.A (n_104), .B (n_78), .Y (n_109));
  sky130_fd_sc_hd__nand4_1 g5556(.A (n_103), .B (n_94), .C (n_82), .D
       (n_99), .Y (n_108));
  sky130_fd_sc_hd__a21o_1 g5557(.A1 (n_80), .A2 (n_19), .B1 (n_76), .X
       (n_107));
  sky130_fd_sc_hd__nand2_1 g5558(.A (n_81), .B (n_43), .Y (n_106));
  sky130_fd_sc_hd__o21ai_1 g5559(.A1 (n_30), .A2 (n_89), .B1 (n_95), .Y
       (n_105));
  sky130_fd_sc_hd__nand2_1 g5560(.A (n_80), .B (n_19), .Y (n_104));
  sky130_fd_sc_hd__nor2_2 g5561(.A (n_83), .B (n_100), .Y (n_103));
  sky130_fd_sc_hd__nor2_2 g5562(.A (n_87), .B (n_96), .Y (n_102));
  sky130_fd_sc_hd__xnor2_1 g5563(.A (n_64), .B (n_93), .Y (n_101));
  sky130_fd_sc_hd__a21oi_2 g5564(.A1 (n_77), .A2 (n_74), .B1 (n_45), .Y
       (n_100));
  sky130_fd_sc_hd__nand2_1 g5565(.A (n_88), .B (n_43), .Y (n_99));
  sky130_fd_sc_hd__nand2_1 g5566(.A (n_63), .B (n_92), .Y (n_98));
  sky130_fd_sc_hd__a21oi_1 g5567(.A1 (n_60), .A2 (n_1), .B1 (n_86), .Y
       (n_97));
  sky130_fd_sc_hd__nand2_1 g5568(.A (n_73), .B (n_85), .Y (n_96));
  sky130_fd_sc_hd__o221a_1 g5569(.A1 (n_31), .A2 (n_61), .B1 (n_36),
       .B2 (n_59), .C1 (n_67), .X (n_95));
  sky130_fd_sc_hd__clkinv_1 g5570(.A (n_91), .Y (n_94));
  sky130_fd_sc_hd__inv_1 g5571(.A (n_92), .Y (n_93));
  sky130_fd_sc_hd__nand2_1 g5572(.A (n_71), .B (n_66), .Y (n_91));
  sky130_fd_sc_hd__o31a_1 g5573(.A1 (b[1]), .A2 (n_3), .A3 (n_59), .B1
       (n_68), .X (n_90));
  sky130_fd_sc_hd__nor2_1 g5574(.A (n_69), .B (n_60), .Y (n_89));
  sky130_fd_sc_hd__o211ai_1 g5575(.A1 (n_23), .A2 (n_47), .B1 (n_40),
       .C1 (n_57), .Y (n_88));
  sky130_fd_sc_hd__o21ai_1 g5576(.A1 (n_48), .A2 (n_34), .B1 (n_72), .Y
       (n_87));
  sky130_fd_sc_hd__nand2_2 g5577(.A (n_70), .B (n_15), .Y (n_92));
  sky130_fd_sc_hd__nand3_1 g5578(.A (n_53), .B (n_50), .C (n_33), .Y
       (n_86));
  sky130_fd_sc_hd__a21oi_1 g5579(.A1 (n_51), .A2 (n_41), .B1 (n_56), .Y
       (n_85));
  sky130_fd_sc_hd__a22oi_1 g5580(.A1 (n_43), .A2 (n_18), .B1 (n_44),
       .B2 (n_12), .Y (n_84));
  sky130_fd_sc_hd__o22ai_1 g5581(.A1 (n_61), .A2 (n_36), .B1 (n_16),
       .B2 (n_59), .Y (n_83));
  sky130_fd_sc_hd__a2bb2oi_1 g5582(.A1_N (n_25), .A2_N (n_49), .B1
       (n_41), .B2 (n_52), .Y (n_82));
  sky130_fd_sc_hd__o2bb2ai_1 g5583(.A1_N (n_64), .A2_N (n_55), .B1
       (n_64), .B2 (n_55), .Y (n_81));
  sky130_fd_sc_hd__nand2_1 g5584(.A (n_46), .B (n_14), .Y (n_77));
  sky130_fd_sc_hd__nand2_1 g5585(.A (n_43), .B (n_34), .Y (n_76));
  sky130_fd_sc_hd__nor2_1 g5586(.A (n_45), .B (n_34), .Y (n_75));
  sky130_fd_sc_hd__nand2_1 g5587(.A (n_55), .B (n_1), .Y (n_80));
  sky130_fd_sc_hd__nand2_1 g5588(.A (n_47), .B (n_65), .Y (n_74));
  sky130_fd_sc_hd__nand2_1 g5589(.A (n_44), .B (n_34), .Y (n_79));
  sky130_fd_sc_hd__nor2_1 g5590(.A (n_42), .B (n_34), .Y (n_78));
  sky130_fd_sc_hd__a21o_1 g5591(.A1 (n_49), .A2 (n_17), .B1 (n_32), .X
       (n_73));
  sky130_fd_sc_hd__a21o_1 g5592(.A1 (n_48), .A2 (a[3]), .B1 (n_35), .X
       (n_72));
  sky130_fd_sc_hd__a21o_1 g5593(.A1 (n_49), .A2 (a[1]), .B1 (n_35), .X
       (n_71));
  sky130_fd_sc_hd__nand2_2 g5594(.A (n_21), .B (n_14), .Y (n_70));
  sky130_fd_sc_hd__a21o_1 g5595(.A1 (n_41), .A2 (n_29), .B1 (n_27), .X
       (n_69));
  sky130_fd_sc_hd__o21ai_1 g5596(.A1 (n_39), .A2 (n_41), .B1 (n_38), .Y
       (n_68));
  sky130_fd_sc_hd__a22o_1 g5597(.A1 (n_35), .A2 (n_24), .B1 (n_22), .B2
       (a[0]), .X (n_67));
  sky130_fd_sc_hd__nand2_1 g5598(.A (n_54), .B (n_58), .Y (n_66));
  sky130_fd_sc_hd__inv_1 g5599(.A (n_14), .Y (n_65));
  sky130_fd_sc_hd__inv_2 g5601(.A (n_1), .Y (n_64));
  sky130_fd_sc_hd__inv_2 g5603(.A (n_1), .Y (n_63));
  sky130_fd_sc_hd__nand2_1 g5605(.A (n_48), .B (n_28), .Y (n_58));
  sky130_fd_sc_hd__nand2_1 g5606(.A (n_47), .B (n_23), .Y (n_57));
  sky130_fd_sc_hd__nor2_1 g5607(.A (n_40), .B (n_37), .Y (n_56));
  sky130_fd_sc_hd__nand2_1 g5608(.A (n_39), .B (n_7), .Y (n_61));
  sky130_fd_sc_hd__o21ai_1 g5609(.A1 (n_8), .A2 (n_22), .B1 (n_48), .Y
       (n_60));
  sky130_fd_sc_hd__nand2_1 g5610(.A (n_39), .B (b[0]), .Y (n_59));
  sky130_fd_sc_hd__nand2_1 g5611(.A (n_47), .B (n_22), .Y (n_54));
  sky130_fd_sc_hd__a21o_1 g5612(.A1 (n_22), .A2 (a[2]), .B1 (n_35), .X
       (n_53));
  sky130_fd_sc_hd__o22ai_1 g5613(.A1 (b[0]), .A2 (n_15), .B1 (b[1]),
       .B2 (n_24), .Y (n_52));
  sky130_fd_sc_hd__o21ai_1 g5614(.A1 (n_7), .A2 (n_16), .B1 (n_37), .Y
       (n_51));
  sky130_fd_sc_hd__nand3b_1 g5615(.A_N (n_15), .B (n_41), .C (b[0]), .Y
       (n_50));
  sky130_fd_sc_hd__o21ai_2 g5616(.A1 (n_24), .A2 (n_25), .B1 (n_28), .Y
       (n_55));
  sky130_fd_sc_hd__inv_2 g5617(.A (n_47), .Y (n_46));
  sky130_fd_sc_hd__inv_2 g5618(.A (n_45), .Y (n_44));
  sky130_fd_sc_hd__inv_2 g5619(.A (n_42), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g5620(.A (n_40), .Y (n_39));
  sky130_fd_sc_hd__nor2_1 g5621(.A (b[0]), .B (n_16), .Y (n_38));
  sky130_fd_sc_hd__nand3_1 g5622(.A (n_4), .B (op[0]), .C (op[1]), .Y
       (n_49));
  sky130_fd_sc_hd__nand3_2 g5623(.A (n_8), .B (n_5), .C (op[2]), .Y
       (n_48));
  sky130_fd_sc_hd__nand2_4 g5624(.A (n_26), .B (n_28), .Y (n_47));
  sky130_fd_sc_hd__nand2_2 g5625(.A (n_27), .B (op[0]), .Y (n_45));
  sky130_fd_sc_hd__nand2_1 g5626(.A (n_27), .B (n_8), .Y (n_42));
  sky130_fd_sc_hd__nor2_2 g5627(.A (op[0]), .B (n_13), .Y (n_41));
  sky130_fd_sc_hd__nand3_2 g5628(.A (op[0]), .B (op[1]), .C (op[2]), .Y
       (n_40));
  sky130_fd_sc_hd__or2_1 g5629(.A (n_19), .B (n_22), .X (n_33));
  sky130_fd_sc_hd__o21bai_1 g5630(.A1 (b[3]), .A2 (a[3]), .B1_N (n_22),
       .Y (n_32));
  sky130_fd_sc_hd__a21oi_1 g5631(.A1 (a[2]), .A2 (b[1]), .B1 (n_29), .Y
       (n_31));
  sky130_fd_sc_hd__a21boi_1 g5632(.A1 (n_7), .A2 (a[0]), .B1_N (n_14),
       .Y (n_30));
  sky130_fd_sc_hd__nand3_2 g5633(.A (n_2), .B (n_7), .C (a[3]), .Y
       (n_37));
  sky130_fd_sc_hd__o21a_1 g5634(.A1 (n_3), .A2 (n_2), .B1 (n_15), .X
       (n_36));
  sky130_fd_sc_hd__nand3_2 g5635(.A (n_5), .B (op[0]), .C (op[2]), .Y
       (n_35));
  sky130_fd_sc_hd__xnor2_4 g5636(.A (b[3]), .B (a[3]), .Y (n_34));
  sky130_fd_sc_hd__nand2_4 g5637(.A (n_0), .B (n_20), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g5638(.A (n_25), .Y (n_26));
  sky130_fd_sc_hd__clkinv_1 g5639(.A (n_24), .Y (n_23));
  sky130_fd_sc_hd__nand2_1 g5640(.A (n_11), .B (b[1]), .Y (n_21));
  sky130_fd_sc_hd__nand2_2 g5641(.A (n_9), .B (b[2]), .Y (n_20));
  sky130_fd_sc_hd__nor2b_1 g5642(.A (b[1]), .B_N (a[0]), .Y (n_29));
  sky130_fd_sc_hd__nand2_2 g5643(.A (a[1]), .B (b[1]), .Y (n_28));
  sky130_fd_sc_hd__nor2_8 g5644(.A (op[1]), .B (op[2]), .Y (n_27));
  sky130_fd_sc_hd__nor2_8 g5645(.A (b[1]), .B (a[1]), .Y (n_25));
  sky130_fd_sc_hd__nand2_2 g5646(.A (a[0]), .B (b[0]), .Y (n_24));
  sky130_fd_sc_hd__nand2_4 g5647(.A (n_4), .B (op[1]), .Y (n_22));
  sky130_fd_sc_hd__inv_2 g5649(.A (n_17), .Y (n_18));
  sky130_fd_sc_hd__nand2_1 g5650(.A (a[2]), .B (b[2]), .Y (n_19));
  sky130_fd_sc_hd__nand2_4 g5651(.A (n_6), .B (a[2]), .Y (n_0));
  sky130_fd_sc_hd__nand2_1 g5652(.A (op[2]), .B (op[1]), .Y (n_13));
  sky130_fd_sc_hd__nand2_1 g5653(.A (a[3]), .B (b[3]), .Y (n_17));
  sky130_fd_sc_hd__nor2_1 g5654(.A (b[3]), .B (n_3), .Y (n_12));
  sky130_fd_sc_hd__nand2_2 g5655(.A (n_2), .B (a[2]), .Y (n_16));
  sky130_fd_sc_hd__nand2_2 g5656(.A (n_2), .B (a[1]), .Y (n_15));
  sky130_fd_sc_hd__nand2_4 g5657(.A (n_10), .B (b[0]), .Y (n_14));
  sky130_fd_sc_hd__inv_2 g5658(.A (a[1]), .Y (n_11));
  sky130_fd_sc_hd__clkinv_4 g5659(.A (a[0]), .Y (n_10));
  sky130_fd_sc_hd__clkinv_2 g5660(.A (a[2]), .Y (n_9));
  sky130_fd_sc_hd__inv_2 g5661(.A (op[0]), .Y (n_8));
  sky130_fd_sc_hd__inv_2 g5662(.A (b[0]), .Y (n_7));
  sky130_fd_sc_hd__clkinv_2 g5663(.A (b[2]), .Y (n_6));
  sky130_fd_sc_hd__inv_2 g5664(.A (op[1]), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g5665(.A (op[2]), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g5666(.A (a[3]), .Y (n_3));
  sky130_fd_sc_hd__inv_4 g5667(.A (b[1]), .Y (n_2));
endmodule

