
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 19 2025 01:53:05

// Verification Directory fv/synth_wrapper 

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_21, n_22, n_24, n_29, n_30, n_31, n_32, n_33;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_43;
  wire n_48, n_49, n_50, n_51, n_52, n_56, n_58, n_59;
  wire n_60, n_61, n_67, n_68, n_70, n_72, n_73, n_83;
  wire n_84, n_85, n_86, n_89, n_90, n_93, n_95, n_96;
  wire n_99, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_137, n_139, n_140, n_141, n_142;
  wire n_143, n_145, n_147, n_148, n_149, n_153, n_156, n_158;
  wire n_161, n_167, n_170, n_173, n_177, n_179, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_220, n_221, n_222, n_223;
  wire n_226, n_227, n_228, n_229, n_231, n_232, n_233, n_234;
  wire n_237;
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_119), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (n_118), .Q (carry));
  sky130_fd_sc_hd__nand4_2 g5542(.A (n_117), .B (n_107), .C (n_102), .D
       (n_110), .Y (n_119));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_115), .Q (result[2]));
  sky130_fd_sc_hd__nand3_1 g5544(.A (n_109), .B (n_114), .C (n_84), .Y
       (n_118));
  sky130_fd_sc_hd__clkinv_2 g5545(.A (n_116), .Y (n_117));
  sky130_fd_sc_hd__o21ai_2 g5546(.A1 (n_203), .A2 (n_148), .B1 (n_113),
       .Y (n_116));
  sky130_fd_sc_hd__nand4_1 g5547(.A (n_187), .B (n_106), .C (n_90), .D
       (n_111), .Y (n_115));
  sky130_fd_sc_hd__nand2b_1 g5548(.A_N (n_203), .B (n_148), .Y (n_114));
  sky130_fd_sc_hd__nand2_2 g5549(.A (n_148), .B (n_202), .Y (n_113));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_108), .Q (result[1]));
  sky130_fd_sc_hd__nand2_1 g5551(.A (n_101), .B (n_156), .Y (n_111));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_105), .Q (result[0]));
  sky130_fd_sc_hd__nand3_1 g5554(.A (n_189), .B (n_204), .C (n_19), .Y
       (n_110));
  sky130_fd_sc_hd__nand2_1 g5555(.A (n_104), .B (n_204), .Y (n_109));
  sky130_fd_sc_hd__nand4_1 g5556(.A (n_103), .B (n_137), .C (n_142), .D
       (n_99), .Y (n_108));
  sky130_fd_sc_hd__a21o_1 g5557(.A1 (n_189), .A2 (n_19), .B1 (n_205),
       .X (n_107));
  sky130_fd_sc_hd__nand2_1 g5558(.A (n_139), .B (n_43), .Y (n_106));
  sky130_fd_sc_hd__o21ai_1 g5559(.A1 (n_30), .A2 (n_89), .B1 (n_95), .Y
       (n_105));
  sky130_fd_sc_hd__nand2_1 g5560(.A (n_189), .B (n_19), .Y (n_104));
  sky130_fd_sc_hd__nor2_2 g5561(.A (n_83), .B (n_229), .Y (n_103));
  sky130_fd_sc_hd__nor2_2 g5562(.A (n_201), .B (n_96), .Y (n_102));
  sky130_fd_sc_hd__xnor2_1 g5563(.A (n_188), .B (n_93), .Y (n_101));
  sky130_fd_sc_hd__nand2_1 g5565(.A (n_237), .B (n_43), .Y (n_99));
  sky130_fd_sc_hd__nand2_1 g5568(.A (n_73), .B (n_85), .Y (n_96));
  sky130_fd_sc_hd__o221a_1 g5569(.A1 (n_31), .A2 (n_61), .B1 (n_36),
       .B2 (n_59), .C1 (n_67), .X (n_95));
  sky130_fd_sc_hd__inv_1 g5571(.A (n_145), .Y (n_93));
  sky130_fd_sc_hd__o31a_1 g5573(.A1 (b[1]), .A2 (n_3), .A3 (n_59), .B1
       (n_68), .X (n_90));
  sky130_fd_sc_hd__nor2_1 g5574(.A (n_232), .B (n_60), .Y (n_89));
  sky130_fd_sc_hd__nand3_1 g5578(.A (n_140), .B (n_50), .C (n_33), .Y
       (n_86));
  sky130_fd_sc_hd__a21oi_2 g5579(.A1 (n_51), .A2 (n_41), .B1 (n_56), .Y
       (n_85));
  sky130_fd_sc_hd__a22oi_1 g5580(.A1 (n_43), .A2 (n_18), .B1 (n_156),
       .B2 (n_12), .Y (n_84));
  sky130_fd_sc_hd__o22ai_1 g5581(.A1 (n_61), .A2 (n_36), .B1 (n_16),
       .B2 (n_59), .Y (n_83));
  sky130_fd_sc_hd__a21o_1 g5591(.A1 (n_49), .A2 (n_17), .B1 (n_32), .X
       (n_73));
  sky130_fd_sc_hd__a21o_1 g5592(.A1 (1'b1), .A2 (a[3]), .B1 (n_35), .X
       (n_72));
  sky130_fd_sc_hd__nand2_4 g5594(.A (n_14), .B (n_21), .Y (n_70));
  sky130_fd_sc_hd__o21ai_1 g5596(.A1 (n_39), .A2 (n_41), .B1 (n_38), .Y
       (n_68));
  sky130_fd_sc_hd__a22o_1 g5597(.A1 (n_35), .A2 (n_24), .B1 (n_22), .B2
       (a[0]), .X (n_67));
  sky130_fd_sc_hd__nand2_1 g5605(.A (n_48), .B (n_221), .Y (n_58));
  sky130_fd_sc_hd__nor2_1 g5607(.A (n_40), .B (n_37), .Y (n_56));
  sky130_fd_sc_hd__nand2_1 g5608(.A (n_39), .B (n_7), .Y (n_61));
  sky130_fd_sc_hd__o21ai_1 g5609(.A1 (n_8), .A2 (n_177), .B1 (n_48), .Y
       (n_60));
  sky130_fd_sc_hd__nand2_1 g5610(.A (n_39), .B (b[0]), .Y (n_59));
  sky130_fd_sc_hd__o22ai_1 g5613(.A1 (b[0]), .A2 (n_15), .B1 (b[1]),
       .B2 (n_24), .Y (n_52));
  sky130_fd_sc_hd__o21ai_2 g5614(.A1 (n_7), .A2 (n_16), .B1 (n_37), .Y
       (n_51));
  sky130_fd_sc_hd__nand3b_1 g5615(.A_N (n_15), .B (n_41), .C (b[0]), .Y
       (n_50));
  sky130_fd_sc_hd__inv_2 g5619(.A (n_233), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g5620(.A (n_40), .Y (n_39));
  sky130_fd_sc_hd__nor2_1 g5621(.A (b[0]), .B (n_16), .Y (n_38));
  sky130_fd_sc_hd__nand3_1 g5622(.A (n_4), .B (op[0]), .C (op[1]), .Y
       (n_49));
  sky130_fd_sc_hd__nand3_1 g5623(.A (n_8), .B (n_5), .C (op[2]), .Y
       (n_48));
  sky130_fd_sc_hd__nor2_2 g5627(.A (op[0]), .B (n_13), .Y (n_41));
  sky130_fd_sc_hd__nand3_2 g5628(.A (op[0]), .B (op[1]), .C (op[2]), .Y
       (n_40));
  sky130_fd_sc_hd__or2_1 g5629(.A (n_19), .B (n_22), .X (n_33));
  sky130_fd_sc_hd__o21bai_4 g5630(.A1 (b[3]), .A2 (a[3]), .B1_N (n_22),
       .Y (n_32));
  sky130_fd_sc_hd__a21oi_1 g5631(.A1 (a[2]), .A2 (b[1]), .B1 (n_29), .Y
       (n_31));
  sky130_fd_sc_hd__a21boi_0 g5632(.A1 (n_7), .A2 (a[0]), .B1_N (n_222),
       .Y (n_30));
  sky130_fd_sc_hd__nand3_4 g5633(.A (n_173), .B (n_7), .C (a[3]), .Y
       (n_37));
  sky130_fd_sc_hd__o21a_1 g5634(.A1 (n_3), .A2 (n_167), .B1 (n_15), .X
       (n_36));
  sky130_fd_sc_hd__nand3_2 g5635(.A (n_5), .B (op[0]), .C (op[2]), .Y
       (n_35));
  sky130_fd_sc_hd__nand2_4 g5640(.A (n_11), .B (b[1]), .Y (n_21));
  sky130_fd_sc_hd__nor2b_1 g5642(.A (b[1]), .B_N (a[0]), .Y (n_29));
  sky130_fd_sc_hd__nand2_4 g5646(.A (a[0]), .B (b[0]), .Y (n_24));
  sky130_fd_sc_hd__nand2_4 g5647(.A (n_4), .B (op[1]), .Y (n_22));
  sky130_fd_sc_hd__inv_2 g5649(.A (n_17), .Y (n_18));
  sky130_fd_sc_hd__nand2_2 g5650(.A (a[2]), .B (b[2]), .Y (n_19));
  sky130_fd_sc_hd__nand2_2 g5652(.A (op[2]), .B (op[1]), .Y (n_13));
  sky130_fd_sc_hd__nand2_1 g5653(.A (a[3]), .B (b[3]), .Y (n_17));
  sky130_fd_sc_hd__nor2_1 g5654(.A (b[3]), .B (n_3), .Y (n_12));
  sky130_fd_sc_hd__nand2_2 g5655(.A (n_167), .B (a[2]), .Y (n_16));
  sky130_fd_sc_hd__nand2_4 g5656(.A (n_170), .B (a[1]), .Y (n_15));
  sky130_fd_sc_hd__nand2_4 g5657(.A (n_10), .B (b[0]), .Y (n_14));
  sky130_fd_sc_hd__inv_6 g5658(.A (a[1]), .Y (n_11));
  sky130_fd_sc_hd__inv_6 g5659(.A (a[0]), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g5661(.A (op[0]), .Y (n_8));
  sky130_fd_sc_hd__inv_6 g5662(.A (b[0]), .Y (n_7));
  sky130_fd_sc_hd__clkinv_4 g5663(.A (b[2]), .Y (n_6));
  sky130_fd_sc_hd__inv_2 g5664(.A (op[1]), .Y (n_5));
  sky130_fd_sc_hd__inv_6 g5665(.A (op[2]), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g5666(.A (a[3]), .Y (n_3));
  sky130_fd_sc_hd__a2bb2oi_2 g2(.A1_N (a[1]), .A2_N (n_35), .B1
       (n_226), .B2 (n_58), .Y (n_137));
  sky130_fd_sc_hd__xnor2_1 g5669(.A (n_188), .B (n_143), .Y (n_139));
  sky130_fd_sc_hd__or2_1 g5670(.A (a[2]), .B (n_35), .X (n_140));
  sky130_fd_sc_hd__a2bb2oi_1 g5671(.A1_N (n_179), .A2_N (n_49), .B1
       (n_41), .B2 (n_52), .Y (n_142));
  sky130_fd_sc_hd__nor2_8 g5672(.A (a[1]), .B (b[1]), .Y (n_141));
  sky130_fd_sc_hd__o21ai_2 g5673(.A1 (n_141), .A2 (n_24), .B1 (n_221),
       .Y (n_143));
  sky130_fd_sc_hd__nand2_4 g5675(.A (n_70), .B (n_15), .Y (n_145));
  sky130_fd_sc_hd__nand2_4 g5676(.A (n_147), .B (n_161), .Y (n_148));
  sky130_fd_sc_hd__nand2_2 g5677(.A (n_145), .B (n_185), .Y (n_147));
  sky130_fd_sc_hd__clkinv_4 fopt(.A (a[2]), .Y (n_149));
  sky130_fd_sc_hd__inv_2 fopt5680(.A (n_222), .Y (n_153));
  sky130_fd_sc_hd__inv_2 fopt5682(.A (n_158), .Y (n_156));
  sky130_fd_sc_hd__buf_2 fopt5685(.A (n_182), .X (n_161));
  sky130_fd_sc_hd__inv_4 fopt5690(.A (b[1]), .Y (n_170));
  sky130_fd_sc_hd__inv_2 fopt5691(.A (b[1]), .Y (n_173));
  sky130_fd_sc_hd__inv_4 fopt5692(.A (b[1]), .Y (n_167));
  sky130_fd_sc_hd__clkbuf_1 fopt5693(.A (n_22), .X (n_177));
  sky130_fd_sc_hd__inv_1 fopt5694(.A (n_220), .Y (n_179));
  sky130_fd_sc_hd__nand2_4 g5696(.A (n_6), .B (a[2]), .Y (n_182));
  sky130_fd_sc_hd__inv_2 g5697(.A (n_184), .Y (n_185));
  sky130_fd_sc_hd__nand2_4 g5698(.A (n_182), .B (n_183), .Y (n_184));
  sky130_fd_sc_hd__nand2_4 g5699(.A (n_149), .B (b[2]), .Y (n_183));
  sky130_fd_sc_hd__a21oi_1 g5700(.A1 (n_60), .A2 (n_186), .B1 (n_86),
       .Y (n_187));
  sky130_fd_sc_hd__buf_1 g1(.A (n_184), .X (n_186));
  sky130_fd_sc_hd__inv_1 g5701(.A (n_184), .Y (n_188));
  sky130_fd_sc_hd__nand2_1 g5702(.A (n_143), .B (n_184), .Y (n_189));
  sky130_fd_sc_hd__o21ai_1 g5714(.A1 (n_48), .A2 (n_200), .B1 (n_72),
       .Y (n_201));
  sky130_fd_sc_hd__xnor2_4 g5715(.A (a[3]), .B (b[3]), .Y (n_200));
  sky130_fd_sc_hd__nor2_1 g5716(.A (n_158), .B (n_200), .Y (n_202));
  sky130_fd_sc_hd__nand2_2 g5717(.A (n_156), .B (n_200), .Y (n_203));
  sky130_fd_sc_hd__nor2_1 g5718(.A (n_233), .B (n_200), .Y (n_204));
  sky130_fd_sc_hd__nand2_1 g5719(.A (n_43), .B (n_200), .Y (n_205));
  sky130_fd_sc_hd__inv_2 fopt5734(.A (n_141), .Y (n_220));
  sky130_fd_sc_hd__nand2_2 g5735(.A (a[1]), .B (b[1]), .Y (n_221));
  sky130_fd_sc_hd__buf_4 fopt5736(.A (n_14), .X (n_222));
  sky130_fd_sc_hd__nand2_4 g5738(.A (n_220), .B (n_221), .Y (n_223));
  sky130_fd_sc_hd__nand2_1 g5740(.A (n_223), .B (n_177), .Y (n_226));
  sky130_fd_sc_hd__a21oi_2 g5741(.A1 (n_227), .A2 (n_228), .B1 (n_158),
       .Y (n_229));
  sky130_fd_sc_hd__nand3_1 g5742(.A (n_222), .B (n_220), .C (n_221), .Y
       (n_227));
  sky130_fd_sc_hd__nand2_1 g5743(.A (n_223), .B (n_153), .Y (n_228));
  sky130_fd_sc_hd__a21o_1 g5746(.A1 (n_41), .A2 (n_29), .B1 (n_231), .X
       (n_232));
  sky130_fd_sc_hd__nor2_2 g5747(.A (op[1]), .B (op[2]), .Y (n_231));
  sky130_fd_sc_hd__nand2_1 g5748(.A (n_231), .B (n_8), .Y (n_233));
  sky130_fd_sc_hd__nand2_2 g5749(.A (n_234), .B (op[0]), .Y (n_158));
  sky130_fd_sc_hd__nor2_4 g5644_dup(.A (op[1]), .B (op[2]), .Y (n_234));
  sky130_fd_sc_hd__xor2_1 g5751(.A (n_24), .B (n_223), .X (n_237));
endmodule

