
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 11 2025 06:45:44

// Verification Directory fv/synth_wrapper 

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_2, n_10, n_15, n_21, n_27, n_28, n_39, n_41;
  wire n_47, n_48, n_50, n_51, n_52, n_58, n_60, n_63;
  wire n_66, n_68, n_69, n_70, n_71, n_73, n_74, n_77;
  wire n_78, n_80, n_81, n_85, n_86, n_88, n_91, n_101;
  wire n_150, n_168, n_191, n_194, n_211, n_273, n_311, n_312;
  wire n_315, n_319, n_321, n_322, n_323, n_326, n_329, n_330;
  wire n_335, n_336, n_340, n_341, n_374, n_375, n_382, n_387;
  wire n_391, n_410, n_411, n_413, n_415, n_417, n_420, n_421;
  wire n_422, n_423, n_424, n_429, n_430, n_431, n_432, n_450;
  wire n_452, n_453, n_455, n_456, n_458, n_460, n_461, n_469;
  wire n_470, n_471, n_481, n_487, n_489, n_491, n_492, n_493;
  wire n_494, n_504, n_505, n_511, n_512, n_518, n_520, n_524;
  wire n_525, n_533, n_534, n_535, n_538, n_549, n_550, n_602;
  wire n_603, n_607, n_608, n_610, n_611, n_612, n_613, n_620;
  wire n_621, n_622, n_623, n_624, n_625, n_629, n_630, n_631;
  wire n_632, n_633, n_634, n_635, n_636, n_637, n_638, n_639;
  wire n_640, n_642, n_643, n_644, n_646, n_649, n_651, n_652;
  wire n_653, n_654, n_655, n_656, n_657, n_658, n_659, n_660;
  wire n_661, n_662, n_664, n_665, n_666;
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_323), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (n_652), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_642), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_431), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_613), .Q (result[0]));
  sky130_fd_sc_hd__nor2_1 g5387(.A (n_86), .B (n_329), .Y (n_101));
  sky130_fd_sc_hd__nand2_1 g5397(.A (n_74), .B (n_211), .Y (n_91));
  sky130_fd_sc_hd__nand2b_1 g5402(.A_N (n_524), .B (n_608), .Y (n_88));
  sky130_fd_sc_hd__nor3_1 g5406(.A (n_525), .B (n_21), .C (n_524), .Y
       (n_86));
  sky130_fd_sc_hd__a21o_1 g5407(.A1 (1'b1), .A2 (a[3]), .B1 (n_492), .X
       (n_85));
  sky130_fd_sc_hd__a31o_1 g5411(.A1 (n_633), .A2 (n_168), .A3 (a[0]),
       .B1 (n_27), .X (n_81));
  sky130_fd_sc_hd__nand3_1 g5412(.A (n_47), .B (n_52), .C (n_525), .Y
       (n_80));
  sky130_fd_sc_hd__a22o_1 g5414(.A1 (n_492), .A2 (n_665), .B1 (n_341),
       .B2 (a[0]), .X (n_78));
  sky130_fd_sc_hd__mux2i_1 g5415(.A0 (n_646), .A1 (n_455), .S (b[3]),
       .Y (n_77));
  sky130_fd_sc_hd__nand2_1 g5421(.A (n_58), .B (n_489), .Y (n_71));
  sky130_fd_sc_hd__nand2_1 g5422(.A (n_422), .B (n_341), .Y (n_70));
  sky130_fd_sc_hd__nand2_1 g5423(.A (n_422), .B (n_150), .Y (n_69));
  sky130_fd_sc_hd__nand2_1 g5424(.A (n_410), .B (n_524), .Y (n_68));
  sky130_fd_sc_hd__o21ai_1 g5425(.A1 (n_330), .A2 (n_341), .B1 (n_58),
       .Y (n_74));
  sky130_fd_sc_hd__nand2_1 g5427(.A (n_39), .B (n_60), .Y (n_66));
  sky130_fd_sc_hd__nand2_1 g5430(.A (n_41), .B (n_633), .Y (n_63));
  sky130_fd_sc_hd__inv_2 g5433(.A (n_492), .Y (n_60));
  sky130_fd_sc_hd__inv_1 g5437(.A (n_524), .Y (n_52));
  sky130_fd_sc_hd__nand4_1 g5438(.A (n_471), .B (a[2]), .C (op[1]), .D
       (b[2]), .Y (n_51));
  sky130_fd_sc_hd__nand2_1 g5439(.A (n_150), .B (n_168), .Y (n_50));
  sky130_fd_sc_hd__nand3_2 g5442(.A (n_330), .B (n_491), .C (op[2]), .Y
       (n_58));
  sky130_fd_sc_hd__inv_1 g5447(.A (n_47), .Y (n_48));
  sky130_fd_sc_hd__nor2_1 g5450(.A (n_525), .B (n_538), .Y (n_41));
  sky130_fd_sc_hd__nand2_1 g5454(.A (n_538), .B (n_28), .Y (n_47));
  sky130_fd_sc_hd__nand2_1 g5462(.A (a[3]), .B (b[1]), .Y (n_28));
  sky130_fd_sc_hd__nor2_1 g5465(.A (op[1]), .B (op[2]), .Y (n_27));
  sky130_fd_sc_hd__nand2_1 g5474(.A (n_168), .B (a[3]), .Y (n_21));
  sky130_fd_sc_hd__inv_2 g5483(.A (b[3]), .Y (n_15));
  sky130_fd_sc_hd__clkinv_8 g5488(.A (a[1]), .Y (n_10));
  sky130_fd_sc_hd__nand2b_2 g5494(.A_N (n_58), .B (n_511), .Y (n_2));
  sky130_fd_sc_hd__inv_1 g5497(.A (a[2]), .Y (n_39));
  sky130_fd_sc_hd__inv_2 fopt5501(.A (n_665), .Y (n_150));
  sky130_fd_sc_hd__nand2_1 g5526(.A (a[2]), .B (b[2]), .Y (n_191));
  sky130_fd_sc_hd__buf_1 g5528(.A (n_312), .X (n_194));
  sky130_fd_sc_hd__inv_4 fopt5594(.A (a[3]), .Y (n_273));
  sky130_fd_sc_hd__nand3_2 g933(.A (n_315), .B (n_319), .C (n_322), .Y
       (n_323));
  sky130_fd_sc_hd__clkinv_2 g937(.A (n_625), .Y (n_315));
  sky130_fd_sc_hd__nor2_1 g949(.A (n_455), .B (n_511), .Y (n_311));
  sky130_fd_sc_hd__nand2_2 g948(.A (n_535), .B (n_191), .Y (n_312));
  sky130_fd_sc_hd__clkinv_1 g934(.A (n_655), .Y (n_319));
  sky130_fd_sc_hd__nor2_2 g936(.A (n_340), .B (n_321), .Y (n_322));
  sky130_fd_sc_hd__nand4_2 g944(.A (n_660), .B (n_2), .C (n_636), .D
       (n_85), .Y (n_321));
  sky130_fd_sc_hd__nor3_1 g94(.A (b[1]), .B (n_326), .C (n_656), .Y
       (n_329));
  sky130_fd_sc_hd__nand2_4 g98(.A (op[1]), .B (op[2]), .Y (n_326));
  sky130_fd_sc_hd__o31ai_1 g255(.A1 (op[2]), .A2 (n_335), .A3 (n_336),
       .B1 (n_661), .Y (n_340));
  sky130_fd_sc_hd__nand2_1 g260(.A (op[1]), .B (op[0]), .Y (n_335));
  sky130_fd_sc_hd__nor2_1 g261(.A (a[3]), .B (b[3]), .Y (n_336));
  sky130_fd_sc_hd__nand2_2 g258(.A (n_471), .B (op[1]), .Y (n_341));
  sky130_fd_sc_hd__nor2_1 g5637(.A (n_511), .B (n_662), .Y (n_382));
  sky130_fd_sc_hd__nand2_4 g121(.A (n_15), .B (a[3]), .Y (n_374));
  sky130_fd_sc_hd__nand2_4 g122(.A (n_273), .B (b[3]), .Y (n_375));
  sky130_fd_sc_hd__nand2_1 g5643(.A (n_387), .B (n_504), .Y (n_391));
  sky130_fd_sc_hd__inv_1 g114(.A (n_470), .Y (n_387));
  sky130_fd_sc_hd__nand3_1 g1329(.A (n_420), .B (n_424), .C (n_430), .Y
       (n_431));
  sky130_fd_sc_hd__clkinv_1 g1333(.A (n_632), .Y (n_420));
  sky130_fd_sc_hd__nand3_1 g1340(.A (n_330), .B (op[1]), .C (op[2]), .Y
       (n_410));
  sky130_fd_sc_hd__o21ai_1 g1339(.A1 (b[0]), .A2 (n_538), .B1 (n_50),
       .Y (n_411));
  sky130_fd_sc_hd__nand3b_1 g1342(.A_N (n_335), .B (n_415), .C (n_471),
       .Y (n_417));
  sky130_fd_sc_hd__nand2_4 g1344(.A (n_413), .B (n_168), .Y (n_415));
  sky130_fd_sc_hd__inv_2 fopt1354(.A (a[1]), .Y (n_413));
  sky130_fd_sc_hd__clkinv_8 g1348(.A (b[1]), .Y (n_168));
  sky130_fd_sc_hd__nand2_1 g1330(.A (n_421), .B (n_423), .Y (n_424));
  sky130_fd_sc_hd__nand3_1 g1343(.A (n_659), .B (n_80), .C (n_455), .Y
       (n_421));
  sky130_fd_sc_hd__o211ai_1 g1332(.A1 (n_422), .A2 (n_150), .B1
       (n_524), .C1 (n_69), .Y (n_423));
  sky130_fd_sc_hd__nand2_4 g1338(.A (n_415), .B (n_489), .Y (n_422));
  sky130_fd_sc_hd__nand2b_1 g1331(.A_N (n_646), .B (n_429), .Y (n_430));
  sky130_fd_sc_hd__xor2_1 g1335(.A (n_520), .B (n_422), .X (n_429));
  sky130_fd_sc_hd__nor2_1 g1345(.A (b[1]), .B (a[1]), .Y (n_432));
  sky130_fd_sc_hd__a21oi_1 g656(.A1 (n_450), .A2 (n_211), .B1 (n_455),
       .Y (n_456));
  sky130_fd_sc_hd__o21ai_1 g661(.A1 (n_665), .A2 (n_432), .B1 (n_489),
       .Y (n_450));
  sky130_fd_sc_hd__nand2_4 g668(.A (n_505), .B (n_494), .Y (n_211));
  sky130_fd_sc_hd__nand3_4 g663(.A (n_452), .B (n_453), .C (n_330), .Y
       (n_455));
  sky130_fd_sc_hd__inv_2 g676(.A (op[2]), .Y (n_452));
  sky130_fd_sc_hd__inv_2 g673(.A (op[1]), .Y (n_453));
  sky130_fd_sc_hd__inv_6 g677(.A (op[0]), .Y (n_330));
  sky130_fd_sc_hd__inv_2 g670(.A (n_460), .Y (n_461));
  sky130_fd_sc_hd__nand2_2 g671(.A (n_622), .B (n_538), .Y (n_460));
  sky130_fd_sc_hd__inv_2 g665(.A (n_211), .Y (n_458));
  sky130_fd_sc_hd__inv_2 g662(.A (n_455), .Y (n_469));
  sky130_fd_sc_hd__nand2_4 g669(.A (n_505), .B (n_494), .Y (n_470));
  sky130_fd_sc_hd__clkinv_2 g675(.A (op[2]), .Y (n_471));
  sky130_fd_sc_hd__inv_6 g329(.A (a[2]), .Y (n_481));
  sky130_fd_sc_hd__nor2_8 g5655(.A (a[1]), .B (b[1]), .Y (n_487));
  sky130_fd_sc_hd__nand2_4 g5657(.A (b[1]), .B (a[1]), .Y (n_489));
  sky130_fd_sc_hd__nand3_4 g18(.A (n_491), .B (op[0]), .C (op[2]), .Y
       (n_492));
  sky130_fd_sc_hd__inv_6 g19(.A (op[1]), .Y (n_491));
  sky130_fd_sc_hd__nand2_4 g8(.A (n_493), .B (a[2]), .Y (n_494));
  sky130_fd_sc_hd__inv_8 g9(.A (b[2]), .Y (n_493));
  sky130_fd_sc_hd__nand2_4 g223(.A (n_622), .B (n_538), .Y (n_504));
  sky130_fd_sc_hd__nand2_8 g224(.A (n_481), .B (b[2]), .Y (n_505));
  sky130_fd_sc_hd__inv_2 g225(.A (n_511), .Y (n_512));
  sky130_fd_sc_hd__nand2_4 g226(.A (n_374), .B (n_375), .Y (n_511));
  sky130_fd_sc_hd__clkbuf_1 g25(.A (n_620), .X (n_520));
  sky130_fd_sc_hd__inv_8 g28(.A (a[0]), .Y (n_518));
  sky130_fd_sc_hd__nand4_1 g5661(.A (b[0]), .B (op[2]), .C (op[0]), .D
       (op[1]), .Y (n_73));
  sky130_fd_sc_hd__nand3_2 g30(.A (op[2]), .B (op[0]), .C (op[1]), .Y
       (n_524));
  sky130_fd_sc_hd__inv_2 g31(.A (b[0]), .Y (n_525));
  sky130_fd_sc_hd__nand2_2 g70(.A (n_534), .B (n_470), .Y (n_535));
  sky130_fd_sc_hd__o21ai_2 g71(.A1 (n_487), .A2 (n_533), .B1 (n_489),
       .Y (n_534));
  sky130_fd_sc_hd__nand2_2 g72(.A (a[0]), .B (b[0]), .Y (n_533));
  sky130_fd_sc_hd__nand2_8 g5662(.A (n_168), .B (a[1]), .Y (n_538));
  sky130_fd_sc_hd__nand2_4 g60(.A (n_504), .B (n_505), .Y (n_549));
  sky130_fd_sc_hd__nand2_4 g58(.A (n_493), .B (a[2]), .Y (n_550));
  sky130_fd_sc_hd__nor2_2 g5684(.A (n_646), .B (n_512), .Y (n_602));
  sky130_fd_sc_hd__nand2_2 g5685(.A (n_549), .B (n_550), .Y (n_603));
  sky130_fd_sc_hd__o2bb2ai_1 g35(.A1_N (a[0]), .A2_N (n_607), .B1
       (n_607), .B2 (n_656), .Y (n_608));
  sky130_fd_sc_hd__nor2_4 g37(.A (b[1]), .B (b[0]), .Y (n_607));
  sky130_fd_sc_hd__nand2_1 g53(.A (n_610), .B (n_612), .Y (n_613));
  sky130_fd_sc_hd__o211a_1 g55(.A1 (n_73), .A2 (n_48), .B1 (n_88), .C1
       (n_78), .X (n_610));
  sky130_fd_sc_hd__o21ai_1 g54(.A1 (n_74), .A2 (n_81), .B1 (n_611), .Y
       (n_612));
  sky130_fd_sc_hd__xor2_1 g56(.A (a[0]), .B (b[0]), .X (n_611));
  sky130_fd_sc_hd__nand2_4 g5692(.A (n_620), .B (n_621), .Y (n_622));
  sky130_fd_sc_hd__nand2_4 g24(.A (n_518), .B (b[0]), .Y (n_620));
  sky130_fd_sc_hd__nand2_4 g5693(.A (n_10), .B (b[1]), .Y (n_621));
  sky130_fd_sc_hd__nand2_2 g16(.A (n_623), .B (n_624), .Y (n_625));
  sky130_fd_sc_hd__nand2_2 g17(.A (n_603), .B (n_602), .Y (n_623));
  sky130_fd_sc_hd__nand2_1 g5694(.A (n_312), .B (n_311), .Y (n_624));
  sky130_fd_sc_hd__nand3_1 g59(.A (n_629), .B (n_630), .C (n_631), .Y
       (n_632));
  sky130_fd_sc_hd__o21a_1 g5696(.A1 (a[1]), .A2 (n_492), .B1 (n_417),
       .X (n_629));
  sky130_fd_sc_hd__nand2_1 g61(.A (n_70), .B (n_71), .Y (n_630));
  sky130_fd_sc_hd__nand2b_1 g62(.A_N (n_410), .B (n_411), .Y (n_631));
  sky130_fd_sc_hd__nand3_1 g27(.A (n_633), .B (n_635), .C (b[0]), .Y
       (n_636));
  sky130_fd_sc_hd__nor2_1 g5697(.A (op[0]), .B (n_326), .Y (n_633));
  sky130_fd_sc_hd__nor2_1 g29(.A (b[1]), .B (n_634), .Y (n_635));
  sky130_fd_sc_hd__inv_2 g5698(.A (a[2]), .Y (n_634));
  sky130_fd_sc_hd__nand4_1 g207(.A (n_638), .B (n_639), .C (n_640), .D
       (n_666), .Y (n_642));
  sky130_fd_sc_hd__inv_1 g211(.A (n_637), .Y (n_638));
  sky130_fd_sc_hd__nand2_1 g212(.A (n_101), .B (n_91), .Y (n_637));
  sky130_fd_sc_hd__nand2_1 g210(.A (n_456), .B (n_658), .Y (n_639));
  sky130_fd_sc_hd__and3_1 g209(.A (n_63), .B (n_66), .C (n_51), .X
       (n_640));
  sky130_fd_sc_hd__nand2_2 g108(.A (n_461), .B (n_458), .Y (n_643));
  sky130_fd_sc_hd__nand2_1 g109(.A (n_460), .B (n_211), .Y (n_644));
  sky130_fd_sc_hd__nand3_2 g106(.A (n_452), .B (n_453), .C (op[0]), .Y
       (n_646));
  sky130_fd_sc_hd__nand3_1 g46(.A (n_649), .B (n_664), .C (n_651), .Y
       (n_652));
  sky130_fd_sc_hd__nand2_1 g5699(.A (n_194), .B (n_657), .Y (n_649));
  sky130_fd_sc_hd__nand2_1 g47(.A (n_77), .B (a[3]), .Y (n_651));
  sky130_fd_sc_hd__nand2_1 g5701(.A (n_653), .B (n_654), .Y (n_655));
  sky130_fd_sc_hd__nand2_1 g5702(.A (n_391), .B (n_382), .Y (n_653));
  sky130_fd_sc_hd__nand4_1 g5703(.A (n_535), .B (n_469), .C (n_191), .D
       (n_511), .Y (n_654));
  sky130_fd_sc_hd__nand2_1 g5704(.A (n_525), .B (a[2]), .Y (n_656));
  sky130_fd_sc_hd__and2_1 g2(.A (n_469), .B (n_511), .X (n_657));
  sky130_fd_sc_hd__nand2b_1 g5705(.A_N (n_450), .B (n_458), .Y (n_658));
  sky130_fd_sc_hd__nand2b_1 g5706(.A_N (n_73), .B (n_635), .Y (n_659));
  sky130_fd_sc_hd__nand3_2 g5707(.A (n_68), .B (n_607), .C (a[3]), .Y
       (n_660));
  sky130_fd_sc_hd__nand4_1 g5708(.A (n_471), .B (op[1]), .C (b[3]), .D
       (a[3]), .Y (n_661));
  sky130_fd_sc_hd__nand4b_1 g5709(.A_N (op[1]), .B (op[0]), .C (n_550),
       .D (n_471), .Y (n_662));
  sky130_fd_sc_hd__nand3b_1 g5711(.A_N (n_646), .B (n_512), .C (n_603),
       .Y (n_664));
  sky130_fd_sc_hd__nand2_4 g5712(.A (a[0]), .B (b[0]), .Y (n_665));
  sky130_fd_sc_hd__a21o_1 g5713(.A1 (n_643), .A2 (n_644), .B1 (n_646),
       .X (n_666));
endmodule

