
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 11 2025 06:45:39

// Verification Directory fv/synth_wrapper 

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130;
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_130), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (n_129), .Q (carry));
  sky130_fd_sc_hd__nand3_1 g5351(.A (n_125), .B (n_128), .C (n_113), .Y
       (n_130));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_126), .Q (result[2]));
  sky130_fd_sc_hd__nand3_1 g5353(.A (n_124), .B (n_118), .C (n_102), .Y
       (n_129));
  sky130_fd_sc_hd__clkinv_1 g5354(.A (n_127), .Y (n_128));
  sky130_fd_sc_hd__nand2_1 g5355(.A (n_123), .B (n_117), .Y (n_127));
  sky130_fd_sc_hd__nand2_1 g5356(.A (n_5), .B (n_122), .Y (n_126));
  sky130_fd_sc_hd__o22a_1 g5357(.A1 (n_95), .A2 (n_120), .B1 (n_93),
       .B2 (n_116), .X (n_125));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_119), .Q (result[1]));
  sky130_fd_sc_hd__nand2_1 g5359(.A (n_120), .B (n_94), .Y (n_124));
  sky130_fd_sc_hd__nand2_1 g5360(.A (n_120), .B (n_89), .Y (n_123));
  sky130_fd_sc_hd__a21oi_2 g5361(.A1 (n_96), .A2 (n_44), .B1 (n_121),
       .Y (n_122));
  sky130_fd_sc_hd__a21oi_2 g5362(.A1 (n_111), .A2 (n_110), .B1 (n_43),
       .Y (n_121));
  sky130_fd_sc_hd__nand4_1 g5363(.A (n_4), .B (n_115), .C (n_99), .D
       (n_0), .Y (n_119));
  sky130_fd_sc_hd__nand2_2 g5364(.A (n_109), .B (n_6), .Y (n_120));
  sky130_fd_sc_hd__dfrtp_1 \result_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_114), .Q (result[0]));
  sky130_fd_sc_hd__nand2b_1 g5366(.A_N (n_93), .B (n_116), .Y (n_118));
  sky130_fd_sc_hd__nand2_1 g5367(.A (n_116), .B (n_90), .Y (n_117));
  sky130_fd_sc_hd__nand2_1 g5368(.A (n_97), .B (n_108), .Y (n_115));
  sky130_fd_sc_hd__nand2_2 g5369(.A (n_92), .B (n_19), .Y (n_116));
  sky130_fd_sc_hd__o21ai_1 g5371(.A1 (n_38), .A2 (n_103), .B1 (n_106),
       .Y (n_114));
  sky130_fd_sc_hd__nor2_1 g5372(.A (n_107), .B (n_112), .Y (n_113));
  sky130_fd_sc_hd__a21oi_1 g5374(.A1 (n_1), .A2 (n_20), .B1 (n_31), .Y
       (n_112));
  sky130_fd_sc_hd__nand2_2 g5375(.A (n_75), .B (n_105), .Y (n_111));
  sky130_fd_sc_hd__nand2_1 g5376(.A (n_104), .B (n_42), .Y (n_110));
  sky130_fd_sc_hd__nand2_1 g5377(.A (n_75), .B (n_104), .Y (n_109));
  sky130_fd_sc_hd__nand3_1 g5378(.A (n_87), .B (n_80), .C (n_45), .Y
       (n_108));
  sky130_fd_sc_hd__nand4_1 g5379(.A (n_85), .B (n_84), .C (n_61), .D
       (n_2), .Y (n_107));
  sky130_fd_sc_hd__o211a_1 g5381(.A1 (n_73), .A2 (n_48), .B1 (n_78),
       .C1 (n_88), .X (n_106));
  sky130_fd_sc_hd__inv_2 g5383(.A (n_104), .Y (n_105));
  sky130_fd_sc_hd__nor2_1 g5384(.A (n_81), .B (n_74), .Y (n_103));
  sky130_fd_sc_hd__nand2_1 g5385(.A (n_77), .B (a[3]), .Y (n_102));
  sky130_fd_sc_hd__nor2_1 g5387(.A (n_86), .B (n_79), .Y (n_101));
  sky130_fd_sc_hd__nand2_2 g5388(.A (n_82), .B (n_25), .Y (n_104));
  sky130_fd_sc_hd__clkinv_1 g5389(.A (n_98), .Y (n_100));
  sky130_fd_sc_hd__o22a_1 g5390(.A1 (n_55), .A2 (n_65), .B1 (n_36), .B2
       (n_57), .X (n_99));
  sky130_fd_sc_hd__nand3_1 g5391(.A (n_63), .B (n_66), .C (n_51), .Y
       (n_98));
  sky130_fd_sc_hd__o211ai_1 g5392(.A1 (n_32), .A2 (n_54), .B1 (n_53),
       .C1 (n_69), .Y (n_97));
  sky130_fd_sc_hd__o2bb2ai_1 g5393(.A1_N (n_75), .A2_N (n_67), .B1
       (n_67), .B2 (n_75), .Y (n_96));
  sky130_fd_sc_hd__inv_2 g5395(.A (n_94), .Y (n_95));
  sky130_fd_sc_hd__nand2_1 g5396(.A (n_67), .B (n_42), .Y (n_92));
  sky130_fd_sc_hd__nand2_1 g5397(.A (n_74), .B (n_42), .Y (n_91));
  sky130_fd_sc_hd__nor2_1 g5398(.A (n_46), .B (n_45), .Y (n_90));
  sky130_fd_sc_hd__nor2b_1 g5399(.A (n_43), .B_N (n_46), .Y (n_89));
  sky130_fd_sc_hd__nand2b_1 g5402(.A_N (n_53), .B (n_64), .Y (n_88));
  sky130_fd_sc_hd__nand2_1 g5403(.A (n_72), .B (n_35), .Y (n_87));
  sky130_fd_sc_hd__nor2_2 g5404(.A (n_46), .B (n_43), .Y (n_94));
  sky130_fd_sc_hd__nand2_1 g5405(.A (n_44), .B (n_46), .Y (n_93));
  sky130_fd_sc_hd__nor3_1 g5406(.A (n_13), .B (n_21), .C (n_53), .Y
       (n_86));
  sky130_fd_sc_hd__a21o_1 g5407(.A1 (n_58), .A2 (a[3]), .B1 (n_59), .X
       (n_85));
  sky130_fd_sc_hd__nand2_1 g5408(.A (n_68), .B (n_49), .Y (n_84));
  sky130_fd_sc_hd__a21o_1 g5409(.A1 (n_57), .A2 (a[1]), .B1 (n_59), .X
       (n_83));
  sky130_fd_sc_hd__nand2_2 g5410(.A (n_34), .B (n_22), .Y (n_82));
  sky130_fd_sc_hd__a31o_1 g5411(.A1 (n_56), .A2 (n_7), .A3 (a[0]), .B1
       (n_27), .X (n_81));
  sky130_fd_sc_hd__nand3_1 g5412(.A (n_47), .B (n_52), .C (n_13), .Y
       (n_80));
  sky130_fd_sc_hd__a21oi_1 g5413(.A1 (n_55), .A2 (n_53), .B1 (n_40), .Y
       (n_79));
  sky130_fd_sc_hd__a22o_1 g5414(.A1 (n_59), .A2 (n_33), .B1 (n_31), .B2
       (a[0]), .X (n_78));
  sky130_fd_sc_hd__mux2i_1 g5415(.A0 (n_43), .A1 (n_45), .S (b[3]), .Y
       (n_77));
  sky130_fd_sc_hd__nand2_1 g5416(.A (n_70), .B (n_71), .Y (n_76));
  sky130_fd_sc_hd__inv_2 g5417(.A (n_42), .Y (n_75));
  sky130_fd_sc_hd__inv_2 g5420(.A (n_72), .Y (n_73));
  sky130_fd_sc_hd__nand2_1 g5421(.A (n_58), .B (n_37), .Y (n_71));
  sky130_fd_sc_hd__nand2_1 g5422(.A (n_54), .B (n_31), .Y (n_70));
  sky130_fd_sc_hd__nand2_1 g5423(.A (n_54), .B (n_32), .Y (n_69));
  sky130_fd_sc_hd__nand2_1 g5424(.A (n_55), .B (n_53), .Y (n_68));
  sky130_fd_sc_hd__o21ai_1 g5425(.A1 (n_9), .A2 (n_31), .B1 (n_58), .Y
       (n_74));
  sky130_fd_sc_hd__nor2_2 g5426(.A (n_13), .B (n_53), .Y (n_72));
  sky130_fd_sc_hd__nand2_1 g5427(.A (n_39), .B (n_60), .Y (n_66));
  sky130_fd_sc_hd__o21a_1 g5428(.A1 (b[0]), .A2 (n_25), .B1 (n_50), .X
       (n_65));
  sky130_fd_sc_hd__o2bb2ai_1 g5429(.A1_N (a[0]), .A2_N (n_26), .B1
       (n_23), .B2 (n_26), .Y (n_64));
  sky130_fd_sc_hd__nand2_1 g5430(.A (n_41), .B (n_56), .Y (n_63));
  sky130_fd_sc_hd__nand3_1 g5431(.A (n_56), .B (n_35), .C (b[0]), .Y
       (n_61));
  sky130_fd_sc_hd__o21ai_2 g5432(.A1 (n_33), .A2 (n_36), .B1 (n_37), .Y
       (n_67));
  sky130_fd_sc_hd__inv_2 g5433(.A (n_59), .Y (n_60));
  sky130_fd_sc_hd__inv_2 g5436(.A (n_56), .Y (n_55));
  sky130_fd_sc_hd__inv_1 g5437(.A (n_53), .Y (n_52));
  sky130_fd_sc_hd__nand4_1 g5438(.A (n_12), .B (a[2]), .C (op[1]), .D
       (b[2]), .Y (n_51));
  sky130_fd_sc_hd__nand2_1 g5439(.A (n_32), .B (n_7), .Y (n_50));
  sky130_fd_sc_hd__and2_1 g5440(.A (n_26), .B (a[3]), .X (n_49));
  sky130_fd_sc_hd__nand3_4 g5441(.A (n_11), .B (op[2]), .C (op[0]), .Y
       (n_59));
  sky130_fd_sc_hd__nand3_2 g5442(.A (n_9), .B (n_11), .C (op[2]), .Y
       (n_58));
  sky130_fd_sc_hd__nand3_1 g5443(.A (n_12), .B (op[0]), .C (op[1]), .Y
       (n_57));
  sky130_fd_sc_hd__nor2_8 g5444(.A (op[0]), .B (n_18), .Y (n_56));
  sky130_fd_sc_hd__o21ai_4 g5445(.A1 (b[1]), .A2 (a[1]), .B1 (n_37), .Y
       (n_54));
  sky130_fd_sc_hd__nand3_4 g5446(.A (op[0]), .B (op[1]), .C (op[2]), .Y
       (n_53));
  sky130_fd_sc_hd__inv_1 g5447(.A (n_47), .Y (n_48));
  sky130_fd_sc_hd__inv_2 g5448(.A (n_45), .Y (n_44));
  sky130_fd_sc_hd__nor2_2 g5450(.A (n_13), .B (n_25), .Y (n_41));
  sky130_fd_sc_hd__nand3_1 g5451(.A (n_13), .B (n_7), .C (a[2]), .Y
       (n_40));
  sky130_fd_sc_hd__nand2_1 g5452(.A (n_31), .B (a[2]), .Y (n_39));
  sky130_fd_sc_hd__a21boi_1 g5453(.A1 (n_13), .A2 (a[0]), .B1_N (n_34),
       .Y (n_38));
  sky130_fd_sc_hd__nand2_1 g5454(.A (n_25), .B (n_28), .Y (n_47));
  sky130_fd_sc_hd__nand2_2 g5455(.A (n_24), .B (n_29), .Y (n_46));
  sky130_fd_sc_hd__nand3_2 g5456(.A (n_12), .B (n_11), .C (n_9), .Y
       (n_45));
  sky130_fd_sc_hd__nand3_2 g5457(.A (n_11), .B (op[0]), .C (n_12), .Y
       (n_43));
  sky130_fd_sc_hd__nand2_4 g5458(.A (n_6), .B (n_30), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g5459(.A (n_33), .Y (n_32));
  sky130_fd_sc_hd__nand2_2 g5460(.A (n_14), .B (b[2]), .Y (n_30));
  sky130_fd_sc_hd__nand2_1 g5461(.A (n_8), .B (b[3]), .Y (n_29));
  sky130_fd_sc_hd__nand2_1 g5462(.A (a[3]), .B (b[1]), .Y (n_28));
  sky130_fd_sc_hd__nand2_2 g5463(.A (a[1]), .B (b[1]), .Y (n_37));
  sky130_fd_sc_hd__nor2_2 g5464(.A (b[1]), .B (a[1]), .Y (n_36));
  sky130_fd_sc_hd__nor2_1 g5465(.A (op[1]), .B (op[2]), .Y (n_27));
  sky130_fd_sc_hd__nor2b_1 g5466(.A (b[1]), .B_N (a[2]), .Y (n_35));
  sky130_fd_sc_hd__nand2_2 g5467(.A (n_16), .B (b[0]), .Y (n_34));
  sky130_fd_sc_hd__nand2_4 g5468(.A (a[0]), .B (b[0]), .Y (n_33));
  sky130_fd_sc_hd__nand2_4 g5469(.A (n_12), .B (op[1]), .Y (n_31));
  sky130_fd_sc_hd__nand2_1 g5471(.A (n_15), .B (a[3]), .Y (n_24));
  sky130_fd_sc_hd__nand2_1 g5472(.A (n_13), .B (a[2]), .Y (n_23));
  sky130_fd_sc_hd__nand2_1 g5473(.A (n_10), .B (b[1]), .Y (n_22));
  sky130_fd_sc_hd__nand2_1 g5474(.A (n_7), .B (a[3]), .Y (n_21));
  sky130_fd_sc_hd__nand2_1 g5475(.A (a[3]), .B (b[3]), .Y (n_20));
  sky130_fd_sc_hd__nand2_4 g5476(.A (n_17), .B (a[2]), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g5477(.A (a[2]), .B (b[2]), .Y (n_19));
  sky130_fd_sc_hd__nand2_8 g5478(.A (op[2]), .B (op[1]), .Y (n_18));
  sky130_fd_sc_hd__nor2_1 g5479(.A (b[0]), .B (b[1]), .Y (n_26));
  sky130_fd_sc_hd__nand2_4 g5480(.A (n_7), .B (a[1]), .Y (n_25));
  sky130_fd_sc_hd__inv_4 g5481(.A (b[2]), .Y (n_17));
  sky130_fd_sc_hd__inv_4 g5482(.A (a[0]), .Y (n_16));
  sky130_fd_sc_hd__inv_2 g5483(.A (b[3]), .Y (n_15));
  sky130_fd_sc_hd__clkinv_2 g5484(.A (a[2]), .Y (n_14));
  sky130_fd_sc_hd__inv_4 g5485(.A (b[0]), .Y (n_13));
  sky130_fd_sc_hd__inv_8 g5486(.A (op[2]), .Y (n_12));
  sky130_fd_sc_hd__clkinv_8 g5487(.A (op[1]), .Y (n_11));
  sky130_fd_sc_hd__inv_2 g5488(.A (a[1]), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g5489(.A (op[0]), .Y (n_9));
  sky130_fd_sc_hd__inv_2 g5490(.A (a[3]), .Y (n_8));
  sky130_fd_sc_hd__clkinv_8 g5491(.A (b[1]), .Y (n_7));
  sky130_fd_sc_hd__and3_1 g2(.A (n_91), .B (n_101), .C (n_100), .X
       (n_5));
  sky130_fd_sc_hd__and2_1 g5492(.A (n_83), .B (n_76), .X (n_4));
  sky130_fd_sc_hd__xor2_1 g5493(.A (n_34), .B (n_54), .X (n_3));
  sky130_fd_sc_hd__nand2b_1 g5494(.A_N (n_58), .B (n_46), .Y (n_2));
  sky130_fd_sc_hd__o21bai_1 g5495(.A1 (b[3]), .A2 (a[3]), .B1_N (n_57),
       .Y (n_1));
  sky130_fd_sc_hd__nand2b_1 g5496(.A_N (n_43), .B (n_3), .Y (n_0));
endmodule

